// Generated by scripts/build/prepare-svelte-runtime-registry.ts. Do not edit.
export const SVELTE_TOOLCHAIN_VERSIONS = {
  svelte: '5.19.2',
  rollup: '4.28.1',
  svelteLanguage: '6.0.0',
  unocss: '65.4.3',
} as const
