compatibility_flags = ["nodejs_compat"]

compatibility_date = "2025-04-01"
# assets.directory = "./dist"
# assets.binding = "ASSETS"
observability.enabled = true
main = "./dist/_worker.js/index.js"

[[kv_namespaces]]
binding = 'KOALA'
id = '21ec6922e3e446d9984567753c7a3b88'
preview_id = '21ec6922e3e446d9984567753c7a3b88'

[[d1_databases]]
binding = "DB"
database_name = "prod-koala"
database_id = "3cc89d41-3caa-4415-a2dc-46f4af92304a"
migrations_dir = "migrations"

[vars]
DATA_SOURCE = "d1"
CF_PAGES = 1
