compatibility_date = "2024-12-11"

[[kv_namespaces]]
binding = 'KOALA'
id = '21ec6922e3e446d9984567753c7a3b88'
preview_id = '21ec6922e3e446d9984567753c7a3b88'

[[d1_databases]]
binding = "DB"
database_name = "prod-koala"
database_id = "32dd6bfa-e244-402b-bd1b-fab50996e819"
migrations_dir = "migrations"
